### ISSUE TITLE
Log is not configured in developmnet mode

### ISSUE THREAD

**Issue by Amigo-sa** [Amigo-sa/reviewer#4]
Не понятно, для чего нужно присвоение 
app_mode = "development"
ведь в этом случае метод configure_logger не вызывается. Мб надо в любом случае его вызывать? В зависимости от режима можно выставлять разный уровень лога. Для боя - warning, для development - info 

https://github.com/Amigo-sa/reviewer/blob/48ff63ef064fdd8c0452cac289b3a70bbeb4b49f/src/node/node_server.py#L26

**Comment by kirilldemkin** [comment]
До настоящего момента логика была такая: production - то что на сервере, development - то что на локальной машине. Если переменная не определена или явно задана development - логи не конфигурируются и по умолчанию все идет в консоль. Согласен, что название значений переменных ввело в заблуждение - поправлю
